#!/usr/bin/env bash
# Script qui modifie les résolutions DNS locales:
# - localhost -> 127.0.0.2
# - facebook.com -> 8.8.8.8

# Crée une copie du fichier hosts original
cp /etc/hosts ~/hosts.new

# Modifie l'adresse IP de localhost à 127.0.0.2
sed -i 's/127.0.0.1\slocalhost/127.0.0.2 localhost/g' ~/hosts.new

# Ajoute l'entrée pour facebook.com qui pointe vers 8.8.8.8
echo "8.8.8.8 facebook.com" >> ~/hosts.new

# Remplace le fichier hosts original par notre version modifiée
cp -f ~/hosts.new /etc/hosts

# Nettoyer - supprime le fichier temporaire
rm ~/hosts.new
